#!/bin/sh

export TERM=xterm
mark="##job##"

# build new screen
if [ $# -ge 1 ]; then
  if [ $1 = "-a" ]; then
    if [ $# -lt 3 ]; then
      echo "Please input your job-name and job-number!"
      exit
    fi
  #  if [ -n "`grep "$2" ~/bin/mscreen-tool`" ]; then
  #    echo "Your input job's name \"$2\", has already exist"
  #    exit
  #  fi
    echo "Add new screen"
    sed -i "s|$mark|\"$2 $3\"\ \\\\\n      $mark|g" ~/bin/mscreen-tool 
    shift $#
  fi
fi

# build new screen
if [ $# -ge 1 ]; then
  source ~/bin/mscreen-tool
  if [ $1 = "-d" ]; then
    if [ $# -lt 2 ];then
      echo "Please input the job's index!"
      exit
    fi
    delete_job_index_header_line_number=2
    delete_job_index=`expr $2 + $delete_job_index_header_line_number`
    delete_job_name_pid="${jobs[$2]}"
    delete_job_name=($delete_job_name_pid)
    delete_job_pid=${delete_job_name[1]}
    echo "  *******"
    echo "  *******       delete ${delete_job_pid} job"
    echo "  ******* `sed -n ${delete_job_index}p ~/bin/mscreen-tool`" 
    echo "  *******"
    screen -X -S ${delete_job_pid} quit
    sed -i "${delete_job_index}d" ~/bin/mscreen-tool
    shift $#
  fi
fi

source ~/bin/mscreen-tool
#######################################################################

echo "  Screen jobs"
echo "  Your cmd: $@"

index=0
for var in "${jobs[@]}"
do 
  echo -e "  [ $index ] $var"
  ((index++))
done

if [ $# -lt 1 ]; then
  echo -e \
  "-----------------------------------------------------------------------
  WARING: Please inter your job's num!"
  echo -e \
  "-----------------------------------------------------------------------
  Build new screen
    mscreen -b
  Add new screen
    mscreen -a <job name> <job pid>
  Delete one screen job
    mscreen -d <job index>"
  exit
fi

# build new screen
if [ $1 = "-b" ]; then
  echo "New screen"
  screen
  exit
fi

# input must be int
expr $1 + 6 &>/dev/null
if [ $? -ne 0 ]; then
  echo -e \
  "-----------------------------------------------------------------------
  Your input is invalid!"
  exit
fi

# input must less then index
if [ $1 -gt $index ]; then
  echo -e \
  "------------------------------------------------------------------------
  Your input is not in the jobs!"
  exit
fi

id="${jobs[$1]}"
id_=($id)
echo -e "  Use jobs $id "
cmd="screen -r -d ${id_[1]}"
echo $cmd
$cmd
