#!/bin/sh

export TERM=xterm

jobs=("AVS 5674.pts-4.dev1" \
      "tmp 24161.pts-45.dev1" \
      "SmartHome 6572.pts-31.dev1" \
      "tencent 6888.pts-10.dev1" \
      "github 17941.pts-23.dev1" \
      "saipr 2014.pts-10.dev1" \
      "saih2 25861.pts-11.dev1" \
      "zhaoge 9902.pts-18.dev1" \
      "guangheaibo 3472.pts-19.dev1" \
      "qingping 20956.pts-49.dev1" \
      "tencent-s 4519.pts-4.dev1" \
      )

#######################################################################

echo "  Screen jobs"
echo "  Your cmd: $@"

index=0
for var in "${jobs[@]}"
do 
  echo -e "  [ $index ] $var"
  ((index++))
done

if [ $# -lt 1 ]; then
  echo -e \
  "-----------------------------------------------------------------------
  WARING: Please inter your job's num!"
  echo -e \
  "-----------------------------------------------------------------------
  Build new screen
    mscreen -b
  Add new screen
    mscreen -a"
  exit
fi

# build new screen
if [ $1 = "-a" ]; then
  echo "Add new screen"
  vim ~/bin/mscreen
  exit
fi

# build new screen
if [ $1 = "-b" ]; then
  echo "New screen"
  screen
  exit
fi

# input must be int
expr $1 + 6 &>/dev/null
if [ $? -ne 0 ]; then
  echo -e \
  "-----------------------------------------------------------------------
  Your input is invalid!"
  exit
fi

# input must less then index
if [ $1 -gt $index ]; then
  echo -e \
  "------------------------------------------------------------------------
  Your input is not in the jobs!"
  exit
fi

id="${jobs[$1]}"
id_=($id)
echo -e "  Use jobs $id "
cmd="screen -r -d ${id_[1]}"
echo $cmd
$cmd
